### ISSUE TITLE
history version 1.13~ wanted by react router

### ISSUE THREAD

**Issue by jeffreygnatek** [chrishowes/redux-seed#1]
npm ERR! peerinvalid The package history@1.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@1.0.2 wants history@1.13.x

**Comment by chrishowes** [comment]
What version of node / npm are you running?

**Comment by chrishowes** [comment]
In mine (Node: 5.1.0 / NPM: 3.3.12) it's just a WARN, which still passes.

```
npm WARN EPEERINVALID react-router@1.0.2 requires a peer of history@1.13.x but none was installed.
npm WARN EPACKAGEJSON seed-for-jeff@0.1.0 No repository field.
npm WARN EPACKAGEJSON seed-for-jeff@0.1.0 No license field.
```
